version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fitness_tracker
      MYSQL_USER: ft_user
      MYSQL_PASSWORD: ft_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ft_user
      DB_PASS: ft_pass
      DB_NAME: fitness_tracker
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data:
